### ISSUE TITLE
Import not working for me

### ISSUE THREAD

**Issue by ColdVergil** [Daniel-Mendes/import-wishlist#5]
Yeah I log into both accounts and hit the import button but it just loops infinitely. Is there a fix? I've tried on Chrome and Firefox

**Comment by Daniel-Mendes** [comment]
How much games are you trying to import ?

**Comment by ColdVergil** [comment]
> How much games are you trying to import ?

Ehh it's about 113 games haha

**Comment by Daniel-Mendes** [comment]
I've published a new version  0.1.1, you can import more games at the same time now.

**Comment by ColdVergil** [comment]
> I've published a new version 0.1.1, you can import more games at the same time now.

Alright thanks for updating it! I'll wait till it shows on the store and try.

**Comment by Daniel-Mendes** [comment]
It has been published to chrome now

**Comment by ColdVergil** [comment]
> It has been published to chrome now

It worked now! Thanks a lot!!!
