### ISSUE TITLE
Firefox plugin not recognizing account logins

### ISSUE THREAD

**Issue by GoOtterGo** [Daniel-Mendes/import-wishlist#6]
Login promps appear to complete, though the extension does not visibly change. When attempting to connect GOG account, the below window pops up, and the 'Import Wishlist' button produces a 'Please connect to your GOG account.' notification.

See screenshots for results:

![2023-02-17 10_31_27-Mail](https://user-images.githubusercontent.com/4467148/219697826-0ef00a29-0fd9-45e6-8896-78b20c85b4e9.png)

![2023-02-17 10_31_40-Steam Community __ Edit Profile — Mozilla Firefox](https://user-images.githubusercontent.com/4467148/219698517-2cc37922-0437-4d9a-9fb1-2538f67a54b6.png)

![2023-02-17 10_31_18-](https://user-images.githubusercontent.com/4467148/219697823-e0a5fc64-7a39-4c7b-9ebb-25d23b4fa4de.png)

**Comment by Daniel-Mendes** [comment]
I tried with Firefox and v.0.1.1 of my extension and it works, try to clear your browser cache and retry.

**Comment by shadow-identity** [comment]
Having the same issue ._.
